/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NegotiationRouteImport } from './routes/negotiation'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as BrokersIdRouteImport } from './routes/brokers.$id'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as AppDashboardTasksRouteImport } from './routes/_app.dashboard.tasks'
import { Route as AppDashboardNewRouteImport } from './routes/_app.dashboard.new'
import { Route as AppDashboardClientsRouteImport } from './routes/_app.dashboard.clients'
import { Route as AppDashboardEditIdRouteImport } from './routes/_app.dashboard.edit.$id'
import { Route as AppDashboardClientsIdRouteImport } from './routes/_app.dashboard.clients.$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationRoute = NegotiationRouteImport.update({
  id: '/negotiation',
  path: '/negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersIdRoute = BrokersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrokersRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardTasksRoute = AppDashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardNewRoute = AppDashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardClientsRoute = AppDashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardEditIdRoute = AppDashboardEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardClientsIdRoute = AppDashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/checklist': typeof ChecklistRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/negotiation': typeof NegotiationRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/favorites': typeof AppFavoritesRoute
  '/profile': typeof AppProfileRoute
  '/brokers/$id': typeof BrokersIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/dashboard/clients': typeof AppDashboardClientsRouteWithChildren
  '/dashboard/new': typeof AppDashboardNewRoute
  '/dashboard/tasks': typeof AppDashboardTasksRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/clients/$id': typeof AppDashboardClientsIdRoute
  '/dashboard/edit/$id': typeof AppDashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/checklist': typeof ChecklistRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/negotiation': typeof NegotiationRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRoute
  '/favorites': typeof AppFavoritesRoute
  '/profile': typeof AppProfileRoute
  '/brokers/$id': typeof BrokersIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/dashboard/clients': typeof AppDashboardClientsRouteWithChildren
  '/dashboard/new': typeof AppDashboardNewRoute
  '/dashboard/tasks': typeof AppDashboardTasksRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/clients/$id': typeof AppDashboardClientsIdRoute
  '/dashboard/edit/$id': typeof AppDashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/checklist': typeof ChecklistRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/negotiation': typeof NegotiationRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/profile': typeof AppProfileRoute
  '/brokers/$id': typeof BrokersIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/_app/dashboard/clients': typeof AppDashboardClientsRouteWithChildren
  '/_app/dashboard/new': typeof AppDashboardNewRoute
  '/_app/dashboard/tasks': typeof AppDashboardTasksRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/clients/$id': typeof AppDashboardClientsIdRoute
  '/_app/dashboard/edit/$id': typeof AppDashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brokers'
    | '/calculator'
    | '/checklist'
    | '/help'
    | '/history'
    | '/negotiation'
    | '/privacy'
    | '/risk'
    | '/search'
    | '/tools'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/brokers/$id'
    | '/listing/$id'
    | '/dashboard/clients'
    | '/dashboard/new'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brokers'
    | '/calculator'
    | '/checklist'
    | '/help'
    | '/history'
    | '/negotiation'
    | '/privacy'
    | '/risk'
    | '/search'
    | '/tools'
    | '/favorites'
    | '/profile'
    | '/brokers/$id'
    | '/listing/$id'
    | '/dashboard/clients'
    | '/dashboard/new'
    | '/dashboard/tasks'
    | '/dashboard'
    | '/dashboard/clients/$id'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/brokers'
    | '/calculator'
    | '/checklist'
    | '/help'
    | '/history'
    | '/negotiation'
    | '/privacy'
    | '/risk'
    | '/search'
    | '/tools'
    | '/_app/dashboard'
    | '/_app/favorites'
    | '/_app/profile'
    | '/brokers/$id'
    | '/listing/$id'
    | '/_app/dashboard/clients'
    | '/_app/dashboard/new'
    | '/_app/dashboard/tasks'
    | '/_app/dashboard/'
    | '/_app/dashboard/clients/$id'
    | '/_app/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrokersRoute: typeof BrokersRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ChecklistRoute: typeof ChecklistRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  NegotiationRoute: typeof NegotiationRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskRoute: typeof RiskRoute
  SearchRoute: typeof SearchRoute
  ToolsRoute: typeof ToolsRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiation': {
      id: '/negotiation'
      path: '/negotiation'
      fullPath: '/negotiation'
      preLoaderRoute: typeof NegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$id': {
      id: '/brokers/$id'
      path: '/$id'
      fullPath: '/brokers/$id'
      preLoaderRoute: typeof BrokersIdRouteImport
      parentRoute: typeof BrokersRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/tasks': {
      id: '/_app/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof AppDashboardTasksRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/new': {
      id: '/_app/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof AppDashboardNewRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/clients': {
      id: '/_app/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof AppDashboardClientsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/edit/$id': {
      id: '/_app/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof AppDashboardEditIdRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/clients/$id': {
      id: '/_app/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof AppDashboardClientsIdRouteImport
      parentRoute: typeof AppDashboardClientsRoute
    }
  }
}

interface AppDashboardClientsRouteChildren {
  AppDashboardClientsIdRoute: typeof AppDashboardClientsIdRoute
}

const AppDashboardClientsRouteChildren: AppDashboardClientsRouteChildren = {
  AppDashboardClientsIdRoute: AppDashboardClientsIdRoute,
}

const AppDashboardClientsRouteWithChildren =
  AppDashboardClientsRoute._addFileChildren(AppDashboardClientsRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardClientsRoute: typeof AppDashboardClientsRouteWithChildren
  AppDashboardNewRoute: typeof AppDashboardNewRoute
  AppDashboardTasksRoute: typeof AppDashboardTasksRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardEditIdRoute: typeof AppDashboardEditIdRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardClientsRoute: AppDashboardClientsRouteWithChildren,
  AppDashboardNewRoute: AppDashboardNewRoute,
  AppDashboardTasksRoute: AppDashboardTasksRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardEditIdRoute: AppDashboardEditIdRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppFavoritesRoute: AppFavoritesRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BrokersRouteChildren {
  BrokersIdRoute: typeof BrokersIdRoute
}

const BrokersRouteChildren: BrokersRouteChildren = {
  BrokersIdRoute: BrokersIdRoute,
}

const BrokersRouteWithChildren =
  BrokersRoute._addFileChildren(BrokersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BrokersRoute: BrokersRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ChecklistRoute: ChecklistRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  NegotiationRoute: NegotiationRoute,
  PrivacyRoute: PrivacyRoute,
  RiskRoute: RiskRoute,
  SearchRoute: SearchRoute,
  ToolsRoute: ToolsRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
